import org.apache.hadoop.security.proto.RefreshAuthorizationPolicyProtocolProtos.RefreshAuthorizationPolicyProtocolService;
public class FunctionUse18385 {
public void funcUse() {
RefreshAuthorizationPolicyProtocolService refreshauthorizationpolicyprotocolservice = new RefreshAuthorizationPolicyProtocolService();
refreshauthorizationpolicyprotocolservice.getResponsePrototype(null);
}
}