import org.apache.hadoop.security.proto.RefreshAuthorizationPolicyProtocolProtos.RefreshAuthorizationPolicyProtocolService;
public class FunctionUse18386 {
public void funcUse() {
RefreshAuthorizationPolicyProtocolService refreshauthorizationpolicyprotocolservice = new RefreshAuthorizationPolicyProtocolService();
refreshauthorizationpolicyprotocolservice.getRequestPrototype(null);
}
}