import org.apache.hadoop.security.proto.RefreshUserMappingsProtocolProtos.RefreshSuperUserGroupsConfigurationRequestProto;
public class FunctionUse18688 {
public void funcUse() {
RefreshSuperUserGroupsConfigurationRequestProto refreshsuperusergroupsconfigurationrequestproto = new RefreshSuperUserGroupsConfigurationRequestProto();
refreshsuperusergroupsconfigurationrequestproto.parseFrom(null);
}
}