import org.apache.hadoop.fs.viewfs.RegexMountPointResolvedDstPathReplaceInterceptor;
public class FunctionUse5904 {
public void funcUse() {
RegexMountPointResolvedDstPathReplaceInterceptor regexmountpointresolveddstpathreplaceinterceptor = new RegexMountPointResolvedDstPathReplaceInterceptor();
regexmountpointresolveddstpathreplaceinterceptor.interceptRemainingPath(null);
}
}