import org.apache.hadoop.fs.viewfs.RegexMountPointResolvedDstPathReplaceInterceptor;
public class FunctionUse5910 {
public void funcUse() {
RegexMountPointResolvedDstPathReplaceInterceptor regexmountpointresolveddstpathreplaceinterceptor = new RegexMountPointResolvedDstPathReplaceInterceptor();
regexmountpointresolveddstpathreplaceinterceptor.deserializeFromString(null);
}
}